# Background and foreground colors
background = #050709
foreground = #ffffff

# Standard colors
palette = 0=#050709
palette = 1=#66a773
palette = 2=#d24646
palette = 3=#b4b47b
palette = 4=#727272
palette = 5=#8686ba
palette = 6=#a360a3
palette = 7=#993426

# Bright colors
palette = 8=#4a4a4a
palette = 9=#a3cfa8
palette = 10=#e99999
palette = 11=#dadaba
palette = 12=#adadad
palette = 13=#afafd2
palette = 14=#c296c2
palette = 15=#ffffff
