background            #050709
foreground            #ffffff

# black
color0  #050709
color8  #4a4a4a

# red
color1  #66a773
color9  #a3cfa8

# green
color2  #d24646
color10 #e99999

# yellow
color3  #b4b47b
color11 #dadaba

# blue
color4  #727272
color12 #adadad

# magenta
color5  #8686ba
color13 #afafd2

#cyan
color6  #a360a3
color14 #c296c2

#white
color7  #993426
color15 #ffffff


